# fine-tune models given input datasets


import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms
from pytorch_metric_learning import losses, miners
from pytorch_metric_learning.distances import CosineSimilarity
from torch.utils.data import Dataset, DataLoader


    # ArcFace Loss with Cosine Similarity
    loss_func = losses.ArcFaceLoss(
        num_classes=len(train_loader.dataset.labels.unique()),
        embedding_size=512,
        margin=0.5,
        scale=64,
        distance=CosineSimilarity()  # default and only one
    )






class Evaluator:
    ...

    # generated by ChatGPT
    # def __init__(self, model, train_loader, val_loader):
    #     self.model = model
    #     self.train_loader = train_loader
    #     self.val_loader = val_loader
    
    # def evaluate(self):
    #     self.model.eval()
    #     with torch.no_grad():
    #         train_acc = self._evaluate(self.train_loader)
    #         val_acc = self._evaluate(self.val_loader)
    #     return train_acc, val_acc

    # def _evaluate(self, loader):
    #     correct = 0
    #     total = 0
    #     for images, labels in loader:
    #         images, labels = images.to(device), labels.to(device)
    #         outputs = self.model(images)
    #         _, predicted = torch.max(outputs.data, 1)
    #         total += labels.size(0)
    #         correct += (predicted == labels).sum().item()
    #     return correct / total

